<<<<<<< HEAD
sonar.projectKey=ugioni_unit-tests-jest
sonar.organization=ugioni
=======
sonar.projectKey=vitoriaamaral09_Unit-test
sonar.organization=vitoriaamaral09
>>>>>>> 21626a8f0f273856b7ba7d33d6f4a42512340373
sonar.projectName=Jest Unit Test
sonar.projectVersion=1.0
sonar.sources=./src
sonar.tests=./test
sonar.sourceEncoding=UTF-8
<<<<<<< HEAD
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
=======
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
>>>>>>> 21626a8f0f273856b7ba7d33d6f4a42512340373
