name: Build and Tests

on:
  push:
<<<<<<< HEAD
    branches: [ master ]
  pull_request:
    branches: [ master ]
=======
    branches: [ main ]
  pull_request:
    branches: [ main ]
>>>>>>> 21626a8f0f273856b7ba7d33d6f4a42512340373
  schedule:   
    - cron: '0 12 * * *'

jobs:
  build:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
    - uses: actions/checkout@v6.0.2
    - name: Use Node.js 22
      uses: actions/setup-node@v6.3.0
=======
    - uses: actions/checkout@v5.0.0
    - name: Use Node.js 22
      uses: actions/setup-node@v4.4.0
>>>>>>> 21626a8f0f273856b7ba7d33d6f4a42512340373
      with:
        node-version: 22
        cache: 'npm'
    - run: npm install      
    - run: npm run coverage

  sonarcloud:
    name: Run SonarCloud
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - name: Official SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7.0.0
=======
      - uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
      - name: Official SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.3.0
>>>>>>> 21626a8f0f273856b7ba7d33d6f4a42512340373
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
